version: '3'
services:
  astro:
    build: 
        context: .
        dockerfile: astro-Dockerfile
    deploy:
      resources:
        limits:
          cpus: '2.0'
          memory: 12G   
    ports:
      - "8080:8080"
    volumes:
      - .:/app
      - F:\Astral\backup\backup:/app/data
    command: webserver
    
  streamlit:
    build:
        context: .
        dockerfile: streamlit-Dockerfile
    deploy:
      resources:
        limits:
          cpus: '1.0'
          memory: 4G
    ports:
      - "8501:8501"
    volumes:
      - .:/app
      - F:\Astral\backup\backup:/app/data
    command: "streamlit run ./astrowaves/streamlit/dashboard.py -- --path 'data/'"